# Generated by Django 4.1.5 on 2023-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(null=True, verbose_name="Время публикации"),
        ),
    ]
