# Generated by Django 4.1.3 on 2022-11-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
