# Generated by Django 4.1.3 on 2023-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcategory",
            name="name",
            field=models.CharField(
                max_length=40, unique=True, verbose_name="Название категории"
            ),
        ),
    ]
