# Generated by Django 4.1.3 on 2022-11-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(max_length=1000, verbose_name="Комментарий к посту"),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(verbose_name="Дата публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="", upload_to="blog/images/", verbose_name="Фотография к посту"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.TimeField(verbose_name="Время публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
