# Generated by Django 4.1.3 on 2023-01-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cat_posts",
                to="blog.modelcategory",
                verbose_name="Категория",
            ),
        ),
    ]
