# Generated by Django 4.1.3 on 2022-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_body_alter_post_date_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(max_length=1000, verbose_name="Основной текст"),
        ),
    ]
