# Generated by Django 4.1.3 on 2022-12-10 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Дата публикации"
            ),
        ),
    ]
