# Generated by Django 4.1.3 on 2023-01-25 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0006_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайкнуть",
            ),
        ),
    ]
