# Generated by Django 4.1.3 on 2023-01-25 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0008_alter_post_likes_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                null=True,
                related_name="liked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайкнуть",
            ),
        ),
    ]
