# Generated by Django 4.1.3 on 2023-01-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                null=True,
                related_name="post_likes",
                to="blog.like",
                verbose_name="Лайкнуть",
            ),
        ),
    ]
